Config validator
FilipT03/nasp-project pull request #32
Opened 2024-01-17 19:52 UTC by lazarnagulov

2024-01-18 09:54 UTC, Nikola352 requested changes
WalConfig.SegmentSize should be uint64, not int.

2024-01-18 10:40 UTC, Nikola352 approved these changes

2024-01-18 11:28 UTC, cetkovicaleksa approved these changes
😃

2024-01-23 10:43 UTC, FilipT03 approved these changes

2024-01-24 16:19 UTC, milanlazarevic approved these changes

2024-01-24 20:04 UTC, closed without merging